services:
  mf1:
    build:
      context: .
      dockerfile: Dockerfile
      target: mf1
      args:
        - MF1_URL=http://localhost:3001
        - MF2_URL=http://localhost:3002
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mf2:
    build:
      context: .
      dockerfile: Dockerfile
      target: mf2
      args:
        - MF2_URL=http://localhost:3002
    ports:
      - '3002:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
